In [125]:
import torch
from torch import nn 

In [126]:
vocab_size = 10

In [136]:
class RNN(nn.Module):

    def __init__(self,dim,output_size):
        super().__init__()
        self.dim = dim
        self.Wx = nn.Linear(dim,dim)
        self.Wh = nn.Linear(dim,dim)
        self.sigmoid = nn.Sigmoid()
        self.Wy = nn.Linear(dim,output_size)
        
    def hiddend_state(self, batch_size):
        return torch.zeros(1, self.dim)
        
    def forward(self,x,h):
        h = self.sigmoid(self.Wx(x) + self.Wh(h))
        logits = self.Wy(h)
        return h,logits

In [138]:
class Seq2Seq(nn.Module):

    def __init__(self,dim,output_size):
        super().__init__()
        self.rnn = RNN(output_size)   

In [139]:
text = """First, should you want to get a PhD? I was in a fortunate position of knowing since young age that I really wanted a PhD. Unfortunately it wasn’t for any very well-thought-through considerations: First, I really liked school and learning things and I wanted to learn as much as possible, and second, I really wanted to be like Gordon Freeman from the game Half-Life (who has a PhD from MIT in theoretical physics). I loved that game. But what if you’re more sensible in making your life’s decisions? Should you want to do a PhD? There’s a very nice Quora thread and in the summary of considerations that follows I’ll borrow/restate several from Justin/Ben/others there. I’ll assume that the second option you are considering is joining a medium-large company (which is likely most common). Ask yourself if you find the following properties appealing:

Freedom. A PhD will offer you a lot of freedom in the topics you wish to pursue and learn about. You’re in charge. Of course, you’ll have an adviser who will impose some constraints but in general you’ll have much more freedom than you might find elsewhere.

Ownership. The research you produce will be yours as an individual. Your accomplishments will have your name attached to them. In contrast, it is much more common to “blend in” inside a larger company. A common feeling here is becoming a “cog in a wheel”.

Exclusivity. There are very few people who make it to the top PhD programs. You’d be joining a group of a few hundred distinguished individuals in contrast to a few tens of thousands (?) that will join some company.

Status. Regardless of whether it should be or not, working towards and eventually getting a PhD degree is culturally revered and recognized as an impressive achievement. You also get to be a Doctor; that’s awesome.

Personal freedom. As a PhD student you’re your own boss. Want to sleep in today? Sure. Want to skip a day and go on a vacation? Sure. All that matters is your final output and no one will force you to clock in from 9am to 5pm. Of course, some advisers might be more or less flexible about it and some companies might be as well, but it’s a true first order statement.

Maximizing future choice. Joining a PhD program doesn’t close any doors or eliminate future employment/lifestyle options. You can go one way (PhD -> anywhere else) but not the other (anywhere else -> PhD -> academia/research; it is statistically less likely). Additionally (although this might be quite specific to applied ML), you’re strictly more hirable as a PhD graduate or even as a PhD dropout and many companies might be willing to put you in a more interesting position or with a higher starting salary. More generally, maximizing choice for the future you is a good heuristic to follow.

Maximizing variance. You’re young and there’s really no need to rush. Once you graduate from a PhD you can spend the next ~50 years of your life in some company. Opt for more variance in your experiences.

Personal growth. PhD is an intense experience of rapid growth (you learn a lot) and personal self-discovery (you’ll become a master of managing your own psychology). PhD programs (especially if you can make it into a good one) also offer a high density of exceptionally bright people who will become your best friends forever.

Expertise. PhD is probably your only opportunity in life to really drill deep into a topic and become a recognized leading expert in the world at something. You’re exploring the edge of our knowledge as a species, without the burden of lesser distractions or constraints. There’s something beautiful about that and if you disagree, it could be a sign that PhD is not for you.

The disclaimer. I wanted to also add a few words on some of the potential downsides and failure modes. The PhD is a very specific kind of experience that deserves a large disclaimer. You will inevitably find yourself working very hard (especially before paper deadlines). You need to be okay with the suffering and have enough mental stamina and determination to deal with the pressure. At some points you will lose track of what day of the week it is and go on a diet of leftover food from the microkitchens. You’ll sit exhausted and alone in the lab on a beautiful, sunny Saturday scrolling through Facebook pictures of your friends having fun on exotic trips, paid for by their 5-10x larger salaries. You will have to throw away 3 months of your work while somehow keeping your mental health intact. You’ll struggle with the realization that months of your work were spent on a paper with a few citations while your friends do exciting startups with TechCrunch articles or push products to millions of people. You’ll experience identity crises during which you’ll question your life decisions and wonder what you’re doing with some of the best years of your life. As a result, you should be quite certain that you can thrive in an unstructured environment in the pursuit research and discovery for science. If you’re unsure you should lean slightly negative by default. Ideally you should consider getting a taste of research as an undergraduate on a summer research program before before you decide to commit. In fact, one of the primary reasons that research experience is so desirable during the PhD hiring process is not the research itself, but the fact that the student is more likely to know what they’re getting themselves into.

I should clarify explicitly that this post is not about convincing anyone to do a PhD, I’ve merely tried to enumerate some of the common considerations above. The majority of this post focuses on some tips/tricks for navigating the experience once if you decide to go for it (which we’ll see shortly, below).

Lastly, as a random thought I heard it said that you should only do a PhD if you want to go into academia. In light of all of the above I’d argue that a PhD has strong intrinsic value - it’s an end by itself, not just a means to some end (e.g. academic job).

Getting into a PhD program: references, references, references. Great, you’ve decided to go for it. Now how do you get into a good PhD program? The first order approximation is quite simple - by far most important component are strong reference letters. The ideal scenario is that a well-known professor writes you a letter along the lines of: “Blah is in top 5 of students I’ve ever worked with. She takes initiative, comes up with her own ideas, and gets them to work.” The worst letter is along the lines of: “Blah took my class. She did well.” A research publication under your belt from a summer research program is a very strong bonus, but not absolutely required provided you have strong letters. In particular note: grades are quite irrelevant but you generally don’t want them to be too low. This was not obvious to me as an undergrad and I spent a lot of energy on getting good grades. This time should have instead been directed towards research (or at the very least personal projects), as much and as early as possible, and if possible under supervision of multiple people (you’ll need 3+ letters!). As a last point, what won’t help you too much is pestering your potential advisers out of the blue. They are often incredibly busy people and if you try to approach them too aggressively in an effort to impress them somehow in conferences or over email this may agitate them.

Picking the school. Once you get into some PhD programs, how do you pick the school? It’s easy, join Stanford! Just kidding. More seriously, your dream school should 1) be a top school (not because it looks good on your resume/CV but because of feedback loops; top schools attract other top people, many of whom you will get to know and work with) 2) have a few potential advisers you would want to work with. I really do mean the “few” part - this is very important and provides a safety cushion for you if things don’t work out with your top choice for any one of hundreds of reasons - things in many cases outside of your control, e.g. your dream professor leaves, moves, or spontaneously disappears, and 3) be in a good environment physically. I don’t think new admits appreciate this enough: you will spend 5+ years of your really good years living near the school campus. Trust me, this is a long time and your life will consist of much more than just research."""

In [144]:
chars = list(set(text))

In [151]:
char2id = {c:i for i,c in enumerate(chars)}
id2char = {i:c for i,c in enumerate(chars)}

In [154]:
tokens = [char2id[c] for c in text]

In [157]:
import random

In [162]:
def get_random_x_y(tokens,seq_len):
    i = random.randint(0,len(tokens)-seq_len-2)
    seq = tokens[i:i+seq_len+1]
    x = seq[:-1]
    y = seq[1:]
    return x,y  

In [165]:
get_random_x_y(tokens,5)

([45, 48, 26, 53, 11], [48, 26, 53, 11, 8])

In [148]:
from torch.optim import Adam

In [129]:
x = torch.zeros((1,1,3))

In [130]:
y = torch.LongTensor([5])

In [131]:
y.shape

torch.Size([1])

In [132]:
optimizer = Adam(rnn.parameters(),lr=3e-4)
criterion = nn.CrossEntropyLoss()
rnn = RNN(3,vocab_size)


In [133]:
for n in rnn.parameters():
    print(n)

Parameter containing:
tensor([[ 0.3527,  0.2079, -0.4963],
        [-0.4626, -0.5038,  0.3728],
        [-0.2397, -0.1835,  0.4137]], requires_grad=True)
Parameter containing:
tensor([-0.4653, -0.2420,  0.4055], requires_grad=True)
Parameter containing:
tensor([[-0.4135,  0.3189, -0.5262],
        [ 0.3271,  0.2444, -0.1327],
        [-0.1981, -0.1310, -0.3018]], requires_grad=True)
Parameter containing:
tensor([ 0.3760,  0.1427, -0.5118], requires_grad=True)
Parameter containing:
tensor([[ 0.5293, -0.3943,  0.1277],
        [ 0.5323, -0.0481, -0.5705],
        [-0.2903, -0.0178,  0.5487],
        [ 0.2065, -0.1451, -0.1404],
        [-0.5414, -0.2549,  0.5555],
        [ 0.4923, -0.5752,  0.1124],
        [-0.4802,  0.2080,  0.4433],
        [ 0.2605,  0.2785,  0.2745],
        [ 0.5128, -0.2100,  0.3447],
        [-0.4318, -0.0462,  0.1224]], requires_grad=True)
Parameter containing:
tensor([ 0.0057, -0.4894,  0.3295, -0.5227, -0.5501, -0.3207,  0.3060, -0.1866,
         0.2037, -0.5

In [134]:
for epoch in range(100):
    h = rnn.hiddend_state(1)
    h,logits = rnn(x,h)
    loss = criterion(logits.view(-1,logits.shape[-1]),y)
    print(loss,h)
    optimizer.zero_grad()
    loss.backward()
    nn.utils.clip_grad_norm_(rnn.parameters(), 1)
    optimizer.step()

tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllLossBackward0>) tensor([[[0.4777, 0.4752, 0.4735]]], grad_fn=<SigmoidBackward0>)
tensor(2.6041, grad_fn=<NllL